name: Build Pandoc (Linux)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ghc cabal-install make

      - name: Set Up Haskell Environment
        run: |
          cabal update
          cabal build --only-dependencies

      - name: Build Pandoc
        run: |
          cabal build all --enable-tests

      - name: Upload Pandoc Binary
        uses: actions/upload-artifact@v4
        with:
          name: pandoc-linux
          path: dist-newstyle/build/*/pandoc
