name: Build Pandoc (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          choco install haskell-stack -y
          refreshenv
          stack upgrade
        shell: powershell

      - name: Set up Cabal
        run: |
          cabal update
          cabal build --only-dependencies
        shell: powershell

      - name: Build Pandoc
        run: |
          cabal build all
        shell: powershell

      - name: Upload Pandoc Binary
        uses: actions/upload-artifact@v4
        with:
          name: pandoc-windows
          path: dist-newstyle\build\*\pandoc\*\build\pandoc\pandoc.exe
