name: Build Pandoc (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Stack
        run: choco install haskell-stack

      - name: Build Pandoc
        run: |
          stack upgrade
          git submodule update --init --recursive
          stack setup
          stack build

      - name: Upload Pandoc Executable
        uses: actions/upload-artifact@v3
        with:
          name: pandoc-windows
          path: |
            .stack-work\install\*\bin\pandoc.exe
