name: Build Pandoc Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Stack
        run: choco install haskell-stack

      - name: Build Pandoc
        run: |
          stack setup
          stack build

      - name: Upload Pandoc Binary
        uses: actions/upload-artifact@v3
        with:
          name: pandoc-windows
          path: dist\build\pandoc\pandoc.exe
